# Gzip compression
gzip             on;
gzip_disable     "msie6";
gzip_vary        on;
gzip_proxied     any;
gzip_comp_level  6;
gzip_types       text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

# Security headers
add_header X-Frame-Options DENY always;
add_header X-Content-Type-Options nosniff always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;
add_header Referrer-Policy "origin" always;


# File upload size limit
client_max_body_size 100M;

# Media files
location /media {
  alias /usr/src/app/media;
}

# Static files
location /static {
  alias /usr/src/app/staticfiles;
}

# Main application
location / {
  try_files /dev/null @django_app;
}

# Allow access to well-known directory
location ~ /\.well-known {
  allow all;
}




