# Generated by Django 5.1.7 on 2025-05-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_options_alter_customerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='is_beautician',
            field=models.BooleanField(default=False, verbose_name='بیوتیشن'),
        ),
    ]
