# Generated by Django 5.1.7 on 2025-05-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customerprofile_is_beautician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_beautician',
            field=models.BooleanField(default=False, verbose_name='بیوتیشن'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='کد تایید'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp_code_created',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد کد تایید'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=11, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
