# Generated by Django 5.1.7 on 2025-05-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف پول ها'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'verbose_name': 'تراکنش کیف پول', 'verbose_name_plural': 'تراکنش های کیف پول'},
        ),
    ]
