# Generated by Django 5.1.7 on 2025-04-29 14:58

import django.db.models.deletion
import django_ckeditor_5.fields
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام برند')),
                ('image', models.ImageField(upload_to='workshop-brands/', verbose_name='لوگو برند')),
            ],
            options={
                'verbose_name': 'برند ورکشاپ',
                'verbose_name_plural': 'برندهای ورکشاپ',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان ورکشاپ')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ برگزاری')),
                ('city', models.CharField(max_length=100, verbose_name='شهر محل برگزاری')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت ورکشاپ (ریال)')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='workshops/', verbose_name='تصویر ورکشاپ')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='workshop.workshopbrand', verbose_name='برند ورکشاپ')),
            ],
            options={
                'verbose_name': 'ورکشاپ',
                'verbose_name_plural': 'ورکشاپ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_en', models.CharField(max_length=255, verbose_name='نام به انگلیسی')),
                ('last_name_en', models.CharField(max_length=255, verbose_name='نام خانوادگی به انگلیسی')),
                ('clinic_name', models.CharField(max_length=255, verbose_name='نام کلینیک')),
                ('city', models.CharField(max_length=100, verbose_name='شهر محل فعالیت')),
                ('address', models.TextField(verbose_name='آدرس محل فعالیت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت ثبت نام')),
                ('barcode', models.CharField(blank=True, max_length=20, unique=True, verbose_name='بارکد شرکت کننده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='workshop.workshop', verbose_name='ورکشاپ')),
            ],
            options={
                'verbose_name': 'ثبت نام ورکشاپ',
                'verbose_name_plural': 'ثبت نام\u200cهای ورکشاپ',
            },
        ),
    ]
