# Generated by Django 5.1.7 on 2025-04-29 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRegistrationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=10, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(max_length=10, verbose_name='وضعیت جدید')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workshop.workshopregistration', verbose_name='ثبت\u200cنام')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت ثبت\u200cنام',
                'verbose_name_plural': 'تاریخچه وضعیت\u200cهای ثبت\u200cنام',
                'ordering': ['-changed_at'],
            },
        ),
    ]
