# Generated by Django 5.1.7 on 2025-05-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_workshopregistrationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='capacity',
            field=models.PositiveIntegerField(default=30, verbose_name='ظرفیت ورکشاپ'),
        ),
    ]
