# Generated by Django 5.1.7 on 2025-05-05 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'پرداخت ناموفق'), ('refunded', 'مسترد شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('total_amount', models.PositiveBigIntegerField(verbose_name='مبلغ کل (ریال)')),
                ('shipping_cost', models.PositiveIntegerField(verbose_name='هزینه ارسال (ریال)')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف (ریال)')),
                ('final_amount', models.PositiveBigIntegerField(verbose_name='مبلغ نهایی (ریال)')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='نام گیرنده')),
                ('receiver_phone', models.CharField(max_length=15, verbose_name='شماره تماس گیرنده')),
                ('receiver_address', models.TextField(verbose_name='آدرس گیرنده')),
                ('receiver_city', models.CharField(max_length=100, verbose_name='شهر گیرنده')),
                ('receiver_postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات سفارش')),
                ('tracking_code', models.CharField(blank=True, max_length=50, verbose_name='کد رهگیری پستی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت واحد (ریال)')),
                ('total_price', models.PositiveBigIntegerField(verbose_name='قیمت کل (ریال)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(max_length=20, verbose_name='وضعیت جدید')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت سفارش',
                'verbose_name_plural': 'تاریخچه وضعیت\u200cهای سفارش',
                'ordering': ['-changed_at'],
            },
        ),
    ]
