# Generated by Django 5.1.7 on 2025-05-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reward_applied',
            field=models.BooleanField(default=False, verbose_name='پاداش اعمال شده'),
        ),
    ]
