# Generated by Django 5.1.7 on 2025-05-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_reward_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unpaid_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ پرداخت نشده (ریال)'),
        ),
    ]
