# Generated by Django 5.1.7 on 2025-05-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_unpaid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='کد رهگیری تیپاکس'),
        ),
    ]
