# Generated by Django 5.1.7 on 2025-06-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pasargad_url_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شناسه تراکنش پاسارگاد'),
        ),
    ]
