# Generated by Django 5.1.7 on 2025-04-23 06:03

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برند')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='مدل محصول')),
            ],
        ),
        migrations.CreateModel(
            name='SkinCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ویژگی درمانی محصول')),
            ],
        ),
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ویژگی محصول')),
            ],
        ),
        migrations.CreateModel(
            name='UsageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع مصرف')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='واحد حجم محصول')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='لاین محصول')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='products.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=6, unique=True, verbose_name='کد محصول')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, verbose_name='اسلاگ محصول')),
                ('volume_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار حجم')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('long_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات بلند')),
                ('price_level_1', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت برای کاربران بیوتیشن')),
                ('price_level_2', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت برای کاربران عادی')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='برند')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.line', verbose_name='لاین محصول')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productmodel', verbose_name='مدل محصول')),
                ('skin_conditions', models.ManyToManyField(blank=True, related_name='products', to='products.skincondition', verbose_name='ویژگی درمانی محصول')),
                ('skin_types', models.ManyToManyField(blank=True, related_name='products', to='products.skintype', verbose_name='ویژگی محصول')),
                ('usage_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.usagetype', verbose_name='نوع مصرف')),
                ('volume_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.volumeunit', verbose_name='واحد حجم')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-images/', verbose_name='تصویر محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
        ),
    ]
