# Generated by Django 5.1.7 on 2025-04-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='اسلاگ لاین'),
        ),
    ]
