# Generated by Django 5.1.7 on 2025-04-23 16:24

from django.db import migrations
from products.utils import create_persian_slug

def update_line_slugs(apps, schema_editor):
    Line = apps.get_model('products', 'Line')
    for line in Line.objects.filter(slug=''):
        line.slug = create_persian_slug(line.name)
        line.save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_line_slug'),
    ]

    operations = [
        migrations.RunPython(update_line_slugs),
    ]
