# Generated by Django 5.1.7 on 2025-05-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'لاین', 'verbose_name_plural': 'لاین\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصول'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'مدل محصول', 'verbose_name_plural': 'مدل\u200cهای محصول'},
        ),
        migrations.AlterModelOptions(
            name='skincondition',
            options={'verbose_name': 'ویژگی درمانی محصول', 'verbose_name_plural': 'ویژگی\u200cهای درمانی محصول'},
        ),
        migrations.AlterModelOptions(
            name='skintype',
            options={'verbose_name': 'نوع پوست', 'verbose_name_plural': 'نوع پوست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='usagetype',
            options={'verbose_name': 'نوع مصرف', 'verbose_name_plural': 'انواع مصرف'},
        ),
        migrations.AlterModelOptions(
            name='volumeunit',
            options={'verbose_name': 'واحد حجم', 'verbose_name_plural': 'واحدهای حجم'},
        ),
        migrations.AlterField(
            model_name='skintype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نوع پوست'),
        ),
    ]
